trigger: none

extends:
  template: pipeline-base-deploy.qml
  parameters:
      buildSteps:
        
        - scripts: echo 'child pipeline 1'
                
        - scripts: echo 'child pipeline 2'